model:
  name: test
  framework: pytorch
  artifact_uri: file:///home/runner/workspace/uploads/7c8a4ecc-8cdd-445e-98cf-45b2784a14ea_best_model.pth
  runtime: python:3.11-cuda12.1
  entrypoint: app:predict
  resources:
    gpu: 1
    cpu: '2'
    mem: 6Gi
signature:
  inputs: []
  outputs: []
