model:
  name: test_sk
  framework: pytorch
  artifact_uri: file:///home/runner/workspace/uploads/f182cb4b-94de-40f6-b44d-954abf6433e6_best_model.pth
  runtime: python:3.11-cuda12.1
  entrypoint: app:predict
  resources:
    gpu: 1
    cpu: '2'
    mem: 6Gi
signature:
  inputs: []
  outputs: []
